#!/usr/bin/env python3
"""Fine-tune an Ultralytics segmentation model for WGISD grape clusters."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data",
        type=Path,
        required=True,
        help="Path to wgisd_grape_seg.yaml generated by prepare_wgisd_yolo_seg.py.",
    )
    parser.add_argument(
        "--model",
        default="yolo11n-seg.pt",
        help="Ultralytics segmentation checkpoint to fine-tune.",
    )
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=8)
    parser.add_argument("--device", default="0")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument(
        "--project",
        type=Path,
        default=Path("runs") / "segment",
        help="Ultralytics project directory.",
    )
    parser.add_argument("--name", default="wgisd_grape_seg")
    parser.add_argument(
        "--output-model",
        type=Path,
        default=Path("models") / "wgisd_grape_seg.pt",
        help="Destination checkpoint copied from the training run's best.pt.",
    )
    parser.add_argument("--exist-ok", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    from ultralytics import YOLO

    data_yaml = args.data.expanduser().resolve()
    output_model = args.output_model.expanduser().resolve()
    project = args.project.expanduser().resolve()

    model = YOLO(args.model)
    results = model.train(
        task="segment",
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        project=str(project),
        name=args.name,
        exist_ok=args.exist_ok,
        plots=False,
        verbose=True,
    )

    save_dir = Path(getattr(results, "save_dir", project / args.name))
    best_model = save_dir / "weights" / "best.pt"
    if not best_model.is_file():
        raise FileNotFoundError(f"Training completed but best.pt was not found: {best_model}")

    output_model.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(best_model, output_model)
    print(f"Copied {best_model} to {output_model}")


if __name__ == "__main__":
    main()
